version: 2

project_name: repo2page

before:
  hooks:
    - go mod tidy

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/repo2page
    ldflags:
      - -s -w -X repo2page/internal/version.Version={{.Version}} -X repo2page/internal/version.Commit={{.Commit}} -X repo2page/internal/version.Date={{.Date}}

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/repo2page
    ldflags:
      - -X repo2page/internal/version.Version={{.Version}} -X repo2page/internal/version.Commit={{.Commit}} -X repo2page/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    # Use zip for windows
    format_overrides:
    - goos: windows
      format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew Tap Support
brews:
  - name: repo2page
    repository:
      owner: imsncht
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/imsncht/repo2page"
    description: "Convert repositories into single, portable structure-preserving documents."
    license: "MIT"
    directory: Formula
    test: |
      system "#{bin}/repo2page --version"

# Scoop Bucket Support (Windows)
scoops:
  - name: repo2page
    repository:
      owner: imsncht
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/imsncht/repo2page"
    description: "Convert repositories into single, portable structure-preserving documents."
    license: "MIT"

# DEB/RPM Packages (Linux)
nfpms:
  - maintainer: "Sanchit Dhale <imsncht@gmail.com>"
    description: "Convert repositories into single, portable structure-preserving documents."
    homepage: "https://github.com/imsncht/repo2page"
    license: "MIT"
    formats:
      - deb
      - rpm
