package formatter

import (
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/imsncht/repo2page/internal/core"
)

// RenderHTML renders the repository into a self-contained HTML document.
func RenderHTML(
	repoName string,
	source string,
	tree string,
	files []core.RenderedFile,
	stats core.Statistics,
	warnings []string,
) string {

	var b strings.Builder

	b.WriteString("<!DOCTYPE html>\n")
	b.WriteString("<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"UTF-8\" />\n")
	b.WriteString(fmt.Sprintf("<title>Repository: %s</title>\n", html.EscapeString(repoName)))
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n")

	// Inline CSS
	b.WriteString("<style>\n")
	b.WriteString(css())
	b.WriteString("</style>\n")
	b.WriteString("</head>\n<body>\n")

	// Header
	b.WriteString("<div class=\"header\">\n")
	b.WriteString(fmt.Sprintf("<h1>Repository: %s</h1>\n", html.EscapeString(repoName)))
	b.WriteString(fmt.Sprintf("<p><strong>Source:</strong> %s</p>\n", html.EscapeString(source)))
	b.WriteString(fmt.Sprintf("<p><strong>Generated:</strong> %s</p>\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf(
		"<p><strong>Files:</strong> %d | <strong>Lines:</strong> %d | <strong>Size:</strong> %d KB</p>\n",
		stats.FileCount,
		stats.TotalLines,
		stats.TotalSizeKB,
	))
	b.WriteString("</div>\n")

	// Directory Tree
	if tree != "" {
		b.WriteString("<div class=\"section\">\n")
		b.WriteString("<h2>Directory Structure</h2>\n")
		b.WriteString("<pre class=\"tree\">")
		b.WriteString(html.EscapeString(tree))
		b.WriteString("</pre>\n")
		b.WriteString("</div>\n")
	}

	// Files
	b.WriteString("<div class=\"section\">\n")
	b.WriteString("<h2>Files</h2>\n")

	for _, file := range files {
		b.WriteString("<div class=\"file\">\n")
		b.WriteString(fmt.Sprintf("<div class=\"file-path\">%s</div>\n", html.EscapeString(file.Path)))
		b.WriteString("<pre><code>")
		b.WriteString(html.EscapeString(file.Content))
		b.WriteString("</code></pre>\n")
		b.WriteString("</div>\n")
	}

	b.WriteString("</div>\n")

	// Warnings
	if len(warnings) > 0 {
		b.WriteString("<div class=\"section warnings\">\n")
		b.WriteString("<h2>Warnings</h2>\n<ul>\n")
		for _, w := range warnings {
			b.WriteString(fmt.Sprintf("<li>%s</li>\n", html.EscapeString(w)))
		}
		b.WriteString("</ul>\n</div>\n")
	}

	// Footer
	b.WriteString("<footer>\n")
	b.WriteString("<p>Generated by <strong>repo2page</strong></p>\n")
	b.WriteString("</footer>\n")

	b.WriteString("</body>\n</html>\n")

	return b.String()
}

// --------------------
// Inline CSS
// --------------------

func css() string {
	return `
body {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
	margin: 40px auto;
	max-width: 900px;
	line-height: 1.6;
	color: #222;
	background: #fff;
}

h1, h2 {
	border-bottom: 2px solid #eaeaea;
	padding-bottom: 0.3em;
}

.header p {
	margin: 0.3em 0;
}

.section {
	margin-top: 40px;
}

pre.tree {
	background: #f8f9fa !important;
	color: #000 !important;
	padding: 16px;
	overflow-x: auto;
}

.file {
	margin-top: 32px;
}

.file-path {
	font-family: monospace;
	background: #f0f0f0;
	padding: 8px;
	border-left: 4px solid #0366d6;
}

pre {
	background: #272822;
	color: #f8f8f2;
	padding: 16px;
	overflow-x: auto;
}

code {
	font-family: Menlo, Monaco, Consolas, monospace;
	font-size: 0.9em;
}

.warnings {
	background: #fff8e1;
	padding: 16px;
	border-left: 4px solid #ffb300;
}

footer {
	margin-top: 60px;
	padding-top: 20px;
	border-top: 1px solid #eaeaea;
	font-size: 0.9em;
	color: #555;
}
`
}
