package formatter

import (
	"fmt"
	"strings"
	"time"

	"github.com/imsncht/repo2page/internal/core"
)

// RenderText renders the repository into a plain text document.
func RenderText(
	repoName string,
	source string,
	tree string,
	files []core.RenderedFile,
	stats core.Statistics,
	warnings []string,
) string {

	var b strings.Builder

	separator := strings.Repeat("=", 80)

	// Header
	b.WriteString(separator + "\n")
	b.WriteString(fmt.Sprintf("REPOSITORY: %s\n", repoName))
	b.WriteString(separator + "\n\n")

	b.WriteString(fmt.Sprintf("Source: %s\n", source))
	b.WriteString(fmt.Sprintf("Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf(
		"Files: %d | Lines: %d | Size: %d KB\n\n",
		stats.FileCount,
		stats.TotalLines,
		stats.TotalSizeKB,
	))

	// Directory Tree
	if tree != "" {
		b.WriteString(separator + "\n")
		b.WriteString("DIRECTORY STRUCTURE\n")
		b.WriteString(separator + "\n\n")
		b.WriteString(tree + "\n\n")
	}

	// Files
	b.WriteString(separator + "\n")
	b.WriteString("FILES\n")
	b.WriteString(separator + "\n\n")

	for _, file := range files {
		b.WriteString(fmt.Sprintf("--- %s ---\n\n", file.Path))
		b.WriteString(file.Content)
		if !strings.HasSuffix(file.Content, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Warnings
	if len(warnings) > 0 {
		b.WriteString(separator + "\n")
		b.WriteString("WARNINGS\n")
		b.WriteString(separator + "\n\n")

		for _, w := range warnings {
			b.WriteString("- " + w + "\n")
		}
		b.WriteString("\n")
	}

	// Footer
	b.WriteString(separator + "\n")
	b.WriteString("Generated by repo2page\n")
	b.WriteString(separator + "\n")

	return b.String()
}
